#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Mar 28 07:49:18 CET 2026
maven-metadata-central-snapshots.xml/@default-central-snapshots-https\://central.sonatype.com/repository/maven-snapshots/.lastUpdated=1774680558766
maven-metadata-central-snapshots.xml.error=Could not transfer metadata tools.jackson\:jackson-bom\:3.2.0-SNAPSHOT/maven-metadata.xml from/to central-snapshots (https\://central.sonatype.com/repository/maven-snapshots)\: Permission denied\: getsockopt
