from pathlib import Path
from html import escape

root = Path(r'C:/VoxxedDays')

def sn(rel_path, start, end):
    path = root / rel_path
    lines = path.read_text(encoding='utf-8').splitlines()
    return "\n".join(f"{i:4d}: {lines[i-1]}" for i in range(start, end + 1) if 1 <= i <= len(lines))

repos = [
{
'name': 'JSON-java',
'summary': 'XML parsing, XML-to-object construction, and multi-pass cleanup remain the main large opportunities.',
'items': [
{'title':'1. XML parse/build in org.json.XML','analysis':'The parser repeatedly builds objects while descending through tags, so hot XML workloads pay both control-flow and allocation cost here.','sources':[('GitRepos/JSON-java-master/src/main/java/org/json/XML.java',337,395,'Current parse path')],'diff':'@@ XML.parse(...)\n- jsonObject = new JSONObject();\n+ jsonObject = borrowObject(tagName);\n+ final boolean forcedList = forcedListCache.contains(tagName);\n+ // defer structural promotion until we know the tag shape'},
{'title':'2. Repeated JSONArray creation in XML.java','analysis':'The current code eagerly allocates new arrays in deep parser branches. A pooled or lazy promotion path would reduce GC pressure on large XML documents.','sources':[('GitRepos/JSON-java-master/src/main/java/org/json/XML.java',390,399,'Force-list branch'),('GitRepos/JSON-java-master/src/main/java/org/json/XML.java',455,463,'Recursive child branch'),('GitRepos/JSON-java-master/src/main/java/org/json/XML.java',958,969,'Object-to-array promotion')],'diff':'@@ XML.parse(...)\n- context.put(tagName, new JSONArray());\n+ JSONArray bucket = context.optJSONArray(tagName);\n+ if (bucket == null) { bucket = new JSONArray(); context.put(tagName, bucket); }\n@@ XML.toString(...)\n- value = new JSONArray(value);\n+ value = singletonArrayView(value);'},
{'title':'3. Deep nested lookup work in XML.java','analysis':'The nested tag/attribute/content branches amplify repeated map lookups and conversion work. Caching common branch state lowers per-node overhead.','sources':[('GitRepos/JSON-java-master/src/main/java/org/json/XML.java',348,387,'Attribute processing loop'),('GitRepos/JSON-java-master/src/main/java/org/json/XML.java',425,486,'Content handling and recursion')],'diff':'@@ XML.parse(...)\n- if (config.getForceList().contains(tagName)) {\n+ final boolean forcedList = forcedListCache.contains(tagName);\n+ final Map<String, XMLXsiTypeConverter<?>> xsiTypeMap = config.getXsiTypeMap();\n+ // turn repeated config and map lookups into once-per-element state'},
{'title':'4. XML.removeEmpty recursive cleanup pass','analysis':'This is a second traversal over already built content. Folding whitespace cleanup into the parse path would remove a full recursive pass.','sources':[('GitRepos/JSON-java-master/src/main/java/org/json/XML.java',500,523,'removeEmpty pass')],'diff':'@@ XML.removeEmpty(...)\n- for (int k = sArray.length()-1; k >= 0; k--) { ... }\n+ if (isWhitespaceOnly(cdata)) { return; }\n+ // suppress empty CDATA before it reaches the object model'},
{'title':'5. XML.unescape second pass over text','analysis':'The code scans the string, creates substrings for entities, then delegates decoding. A single-pass decode avoids repeated substring work.','sources':[('GitRepos/JSON-java-master/src/main/java/org/json/XML.java',190,209,'Entity unescape loop')],'diff':'@@ XML.unescape(String string)\n- final String entity = string.substring(i + 1, semic);\n- sb.append(XMLTokener.unescapeEntity(entity));\n+ appendDecodedEntity(string, i + 1, semic, sb);'},
{'title':'6. JSONML structure-building cost','analysis':'JSONML repeatedly allocates nested arrays and objects and bounces between string and typed values.','sources':[('GitRepos/JSON-java-master/src/main/java/org/json/JSONML.java',83,138,'Recursive parse setup'),('GitRepos/JSON-java-master/src/main/java/org/json/JSONML.java',300,332,'Materialization path')],'diff':'@@ JSONML.parse(...)\n- JSONArray newja = null;\n- JSONObject newjo = null;\n+ JSONArray newja = childArrayPool.acquire();\n+ JSONObject newjo = attributeObjectPool.acquire();\n+ // attach childNodes only if children actually exist'},
{'title':'7. JSONObject construction and serialization','analysis':'JSONObject sits on the broadest surface in the repo. Capacity guesses and fewer repeated conversions during serialization are the easiest wins here.','sources':[('GitRepos/JSON-java-master/src/main/java/org/json/JSONObject.java',2820,2888,'Pretty-print entry point'),('GitRepos/JSON-java-master/src/main/java/org/json/JSONObject.java',274,315,'Key/value parse path')],'diff':'@@ JSONObject.toString(int indentFactor)\n- int initialSize = map.size() * 6;\n+ int initialSize = estimateSerializedSize(map);\n@@ parse(...)\n- Object value = jsonTokener.nextValue();\n+ Object value = parseCachedValue(jsonTokener);'},
{'title':'8. JSONTokener central parser cost','analysis':'JSONTokener builds many short-lived StringBuilders while tokenizing. Reusing buffers would lower parser overhead across almost every workload.','sources':[('GitRepos/JSON-java-master/src/main/java/org/json/JSONTokener.java',330,377,'Quoted string parsing'),('GitRepos/JSON-java-master/src/main/java/org/json/JSONTokener.java',478,520,'Unquoted simple-value parsing')],'diff':'@@ JSONTokener.nextString(char quote)\n- StringBuilder sb = new StringBuilder();\n+ StringBuilder sb = threadLocalBuilder();\n+ sb.setLength(0);\n@@ JSONTokener.nextSimpleValue(char c)\n- StringBuilder sb = new StringBuilder();\n+ StringBuilder sb = threadLocalBuilder();\n+ sb.setLength(0);'},
{'title':'9. XMLTokener and CDL data movement hotspots','analysis':'XMLTokener does token assembly in tight loops, while CDL eagerly turns rows back into strings inside nested iteration.','sources':[('GitRepos/JSON-java-master/src/main/java/org/json/XMLTokener.java',324,360,'Token parsing'),('GitRepos/JSON-java-master/src/main/java/org/json/CDL.java',384,404,'Row materialization')],'diff':'@@ XMLTokener.nextToken()\n- StringBuilder sb;\n+ StringBuilder sb = threadLocalBuilder();\n+ sb.setLength(0);\n@@ CDL.toString(...)\n- sb.append(rowToString(jo.toJSONArray(names), delimiter));\n+ appendRow(sb, jo, names, delimiter);'},
{'title':'10. Harness still too short for steady-state JSON-java profiling','analysis':'The current profiling run executes one short JUnit batch. For a hotspot talk, the harness should drive repeated parse and write loops.','sources':[('flamegraph/repos.json',7,24,'Current JSON-java workload config')],'diff':'@@ flamegraph/repos.json\n- "tests": ["org.json.junit.JSONObjectTest", ...]\n+ "tests": ["org.json.junit.XMLTest", "org.json.junit.JSONMLTest"],\n+ "repeat": 25,\n+ "profiling_mode": "long_running_parse_write"'}
]},
{
'name': 'Commons IO',
'summary': 'The strongest opportunities are waiting and polling waste, per-instance concurrency setup, and temp-dir-heavy test harnesses.',
'items': [
{'title':'1. Test setup dominates too much of the current Commons run','analysis':'The selected tests spend a lot of time creating temp directories and fixtures. That hides the IO inner loops you actually want to explain.','sources':[('flamegraph/repos.json',25,42,'Current Commons IO workload config')],'diff':'@@ flamegraph/repos.json\n- "tests": ["IOUtilsTest", "TailerTest", ...]\n+ "tests": ["IOUtilsCopyTest", "IOUtilsWriteTest", "ReaderInputStreamTest"],\n+ "repeat": 40,\n+ "profiling_mode": "in_memory_copy_loops"'},
{'title':'2. Tailer raw thread and executor creation','analysis':'Tailer currently nudges users toward one thread or one executor per tailer. That is simple but wasteful under fan-out.','sources':[('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/input/Tailer.java',129,189,'Builder thread/executor setup')],'diff':'@@ Tailer.Builder\n- private ExecutorService executorService = Executors.newSingleThreadExecutor(Builder::newDaemonThread);\n+ private ExecutorService executorService = TailerExecutors.sharedSingleConsumer();\n+ // reuse a bounded executor instead of N mostly-idle threads'},
{'title':'3. ReadAheadInputStream per-instance executor cost','analysis':'The class defaults to a single-thread executor per stream instance. That is a high fixed cost when many streams coexist.','sources':[('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/input/ReadAheadInputStream.java',61,166,'Default executor creation')],'diff':'@@ ReadAheadInputStream\n- return Executors.newSingleThreadExecutor(ReadAheadInputStream::newDaemonThread);\n+ return SharedIoExecutors.readAheadPool();'},
{'title':'4. Tailer polling and waiting loop','analysis':'The run loop wakes up, checks metadata, and sleeps again. That is the right place to discuss waiting waste and poll intervals.','sources':[('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/input/Tailer.java',988,1056,'Core polling loop')],'diff':'@@ Tailer.run()\n- final boolean newer = tailable.isNewer(last);\n- final long length = tailable.size();\n- ThreadUtils.sleep(delayDuration);\n+ final ChangeToken token = tailable.awaitChange(last, delayDuration);\n+ if (!token.changed()) { continue; }'},
{'title':'5. ReadAheadInputStream data-path waste on top of concurrency overhead','analysis':'The async refill loop reads until buffers are full or a waiter appears. Coarser-grained refill policy can lower lock transitions and short refill churn.','sources':[('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/input/ReadAheadInputStream.java',426,465,'Async refill loop')],'diff':'@@ asyncReadAhead()\n- do { read = in.read(arr, off, len); ... } while (len > 0 && !isWaiting.get());\n+ while (len >= refillChunk && !isWaiting.get()) {\n+     read = in.read(arr, off, Math.min(len, refillChunk));\n+     ...\n+ }'},
{'title':'6. IOUtils broad-surface copy and line materialization cost','analysis':'IOUtils is reused everywhere, so even moderate inefficiency here multiplies. The line-writing path still creates per-line strings eagerly.','sources':[('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/IOUtils.java',3928,3980,'writeLines materialization path'),('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/IOUtils.java',2579,2593,'Skip loop')],'diff':'@@ IOUtils.writeLines(...)\n- write(line.toString(), output, charset);\n+ appendLine(output, line, charsetEncoder);\n@@\n- writer.write(line.toString());\n+ writeObjectDirect(writer, line);'},
{'title':'7. FileUtils directory traversal amplification','analysis':'Recursive copy paths multiply file listing, canonical path checks, and metadata work. On large trees this can dominate total runtime.','sources':[('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/FileUtils.java',1367,1384,'Recursive directory copy')],'diff':'@@ FileUtils.doCopyDirectory(...)\n- for (final File srcFile : srcFiles) { ... }\n+ Files.walkFileTree(srcRoot, new CopyVisitor(srcRoot, dstRoot, fileFilter, exclusionSet));'},
{'title':'8. PathUtils repeated directory comparison work','analysis':'Comparing roots and then recursively comparing contents is expensive when trees are large. Precomputed relative indexes would avoid repeated deep comparisons.','sources':[('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/file/PathUtils.java',344,357,'Root-directory comparison loop')],'diff':'@@ PathUtils.directoryAndFileContentEquals(...)\n- for (int i = 0; i < sortedList1.size(); i++) { ... }\n+ final Map<Path, PathMetadata> left = indexTree(sortedList1);\n+ final Map<Path, PathMetadata> right = indexTree(sortedList2);'},
{'title':'9. ReaderInputStream and UnsynchronizedBufferedReader conversion/refill loops','analysis':'These classes sit on central translation paths. They are not flashy, but any improvement here can affect a lot of higher-level callers.','sources':[('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/input/ReaderInputStream.java',203,248,'ReaderInputStream encoder buffers'),('GitRepos/commons-io-master/src/main/java/org/apache/commons/io/input/UnsynchronizedBufferedReader.java',214,259,'Buffered reader read path')],'diff':'@@ ReaderInputStream\n- private final CharBuffer encoderIn;\n- private final ByteBuffer encoderOut;\n+ private final CharsetEncoder encoder;\n@@ UnsynchronizedBufferedReader.read()\n- if (pos < end || fillBuf() != EOF) {\n+ if (pos < end || fillBufFastPath() != EOF) {'},
{'title':'10. Commons harness should bias toward steady-state inner loops','analysis':'There is still too much filesystem fixture overhead in the selected profile. The page should show code hotspots, not mostly temp-path creation.','sources':[('flamegraph/repos.json',25,42,'Current Commons IO workload config')],'diff':'@@ flamegraph/repos.json\n- "tests": ["TailerTest", "FileAlterationMonitorTest", ...]\n+ "tests": ["IOUtilsCopyTest", "IOUtilsWriteTest", "ReaderInputStreamTest"],\n+ "repeat": 60,\n+ "profile_target": "copy-convert-buffer"'}
]},
{
'name': 'Jackson-core',
'summary': 'The most important current story is measurement failure, followed by broad parser and buffer candidates like JsonPointer and TextBuffer.',
'items': [
{'title':'1. Profiling still fails to capture runtime samples','analysis':'Until JFR is attached to the right JVM boundary or the workload runs longer, every ranking in Jackson is partly blind.','sources':[('flamegraph/repos.json',43,61,'Current Jackson workload config'),('flamegraph/run_flamegraphs.py',120,180,'Harness JVM argument assembly')],'diff':'@@ run_flamegraphs.py\n- "-DargLine=-XX:StartFlightRecording=filename=..."\n+ "-Dsurefire.argLine=-XX:StartFlightRecording=filename=..."\n+ "-DreuseForks=true"\n@@ repos.json\n+ "repeat": 50,\n+ "profiling_mode": "parser_stress"'},
{'title':'2. JsonPointer segment construction','analysis':'JsonPointer repeatedly slices and rebuilds segments while parsing pointer strings. This is the cleanest large static target in the repo.','sources':[('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/JsonPointer.java',734,778,'Tail parsing and segment extraction')],'diff':'@@ JsonPointer._parseTail(...)\n- fullPath.substring(startOffset + 1, i)\n+ sharedSlice(fullPath, startOffset + 1, i)\n+ // delay materializing Strings until the pointer is actually queried'},
{'title':'3. JsonPointer escaped segment handling','analysis':'The escaped-segment branch allocates a StringBuilder and then appends one char at a time. A reusable scratch buffer would remove repeated tiny allocations.','sources':[('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/JsonPointer.java',748,814,'Escaped segment extraction')],'diff':'@@ JsonPointer._extractEscapedSegment(...)\n- StringBuilder sb = new StringBuilder(32);\n+ StringBuilder sb = scratchBuilder();\n+ sb.setLength(0);'},
{'title':'4. TextBuffer segment combination','analysis':'TextBuffer combines multiple char segments into new Strings and arrays. When inputs are large, segment merges become expensive and broadly visible.','sources':[('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/util/TextBuffer.java',536,573,'Combining segments into a String')],'diff':'@@ TextBuffer.contentsAsString()\n- StringBuilder sb = new StringBuilder(builderLen);\n+ SegmentedStringWriter sb = segmentedWriter(builderLen);\n- _resultString = sb.toString();\n+ _resultString = sb.finish();'},
{'title':'5. TextBuffer broad write and array materialization cost','analysis':'The write and array-copy paths make TextBuffer expensive on broad parser surfaces. Special-casing common shapes would lower steady-state churn.','sources':[('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/util/TextBuffer.java',748,778,'writeTo path'),('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/util/TextBuffer.java',1198,1214,'resultArray path')],'diff':'@@ TextBuffer.resultArray()\n- final char[] result = carr(size);\n+ final char[] result = recycler.allocCharBuffer(size);\n@@ TextBuffer.writeTo(Writer w)\n+ // preserve segment structure longer and use recycler-backed buffers'},
{'title':'6. UTF8StreamJsonParser hot parser branches','analysis':'This class is central enough that avoidable string building and token matching matter.','sources':[('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/json/UTF8StreamJsonParser.java',3421,3439,'Invalid number handling'),('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/json/UTF8StreamJsonParser.java',4278,4298,'Base64 decode loop')],'diff':'@@ UTF8StreamJsonParser._handleInvalidNumberStart(...)\n- String match;\n+ final String match;\n@@ UTF8StreamJsonParser._decodeBase64(...)\n- ByteArrayBuilder builder = _getByteArrayBuilder();\n+ ByteArrayBuilder builder = _reusableByteArrayBuilder();'},
{'title':'7. UTF8DataInputJsonParser mirrored parse overhead','analysis':'The data-input parser repeats the same token and error-building patterns.','sources':[('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/json/UTF8DataInputJsonParser.java',2431,2446,'Invalid number handling')],'diff':'@@ UTF8DataInputJsonParser._handleInvalidNumberStart(...)\n- String match;\n+ final String match;\n+ // use shared literal constants and avoid rebuilding token descriptions'},
{'title':'8. ReaderBasedJsonParser needs a denser reader-backed workload and lower-allocation error path','analysis':'Reader-backed parsing is a distinct route and should not be left unprofiled.','sources':[('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/json/ReaderBasedJsonParser.java',2927,2943,'Base64 and error path')],'diff':'@@ ReaderBasedJsonParser\n- _reportInvalidBase64Char(..., "expected padding character ...");\n+ _reportInvalidBase64Padding(b64variant, ch);\n+ // move repeated message assembly into shared helpers'},
{'title':'9. JsonGenerator writeRaw fallback path','analysis':'The abstract API currently defaults some raw writes back to String-based paths. UTF-8 backends should bypass that conversion whenever possible.','sources':[('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/JsonGenerator.java',900,928,'writeRaw SerializableString fallback')],'diff':'@@ JsonGenerator.writeRaw(SerializableString raw)\n- return writeRaw(raw.getValue());\n+ if (canWriteRawUTF8()) return writeRawUTF8(raw.asUnquotedUTF8());\n+ return writeRaw(raw.getValue());'},
{'title':'10. FilteringParserDelegate and recycler/pool area need cleanup, but with measurement caution','analysis':'FilteringParserDelegate itself admits the traversal logic is hairy. The recycler area is worth investigating too, but not with naive ThreadLocal heuristics.','sources':[('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/filter/FilteringParserDelegate.java',230,278,'Complex nextToken traversal'),('GitRepos/jackson-core-3.x/src/main/java/tools/jackson/core/util/JsonRecyclerPools.java',100,114,'ThreadLocal recycler pool')],'diff':'@@ FilteringParserDelegate.nextToken()\n+ // split into explicit state-machine phases\n@@ JsonRecyclerPools\n+ // keep this under manual review: ThreadLocal is not the same problem as raw thread creation'}
]},
{
'name': 'Log4j2',
'summary': 'The best runtime evidence today sits in control-plane setup around properties, providers, and thread context, but the harness still carries framework noise.',
'items': [
{'title':'1. Current Log4j profiling batch still spends too much time in harness overhead','analysis':'Mockito, System Stubs, and temp-dir infrastructure are visible enough to distort the profile.','sources':[('flamegraph/repos.json',62,79,'Current Log4j workload config')],'diff':'@@ flamegraph/repos.json\n- "tests": ["PropertiesUtilTest", "ProviderUtilTest", ...]\n+ "tests": ["PropertiesUtilTest", "ProviderUtilTest"],\n+ "repeat": 80,\n+ "exclude_mocking_heavy": true'},
{'title':'2. PropertiesUtil charset lookup','analysis':'This is the clearest runtime-visible library hotspot in the passing Log4j run.','sources':[('GitRepos/logging-log4j2-2.x/log4j-api/src/main/java/org/apache/logging/log4j/util/PropertiesUtil.java',248,268,'Charset property path')],'diff':'@@ PropertiesUtil.getCharsetProperty(...)\n- if (Charset.isSupported(charsetName)) { return Charset.forName(charsetName); }\n+ final Charset cached = charsetCache.get(charsetName);\n+ if (cached != null) return cached;\n+ if (Charset.isSupported(charsetName)) return charsetCache.computeIfAbsent(charsetName, Charset::forName);'},
{'title':'3. ProviderUtil startup and provider discovery','analysis':'Provider loading is a startup and control-plane cost center that touches ServiceLoader, classpath resources, and property selection.','sources':[('GitRepos/logging-log4j2-2.x/log4j-api/src/main/java/org/apache/logging/log4j/util/ProviderUtil.java',101,109,'Provider resource load'),('GitRepos/logging-log4j2-2.x/log4j-api/src/main/java/org/apache/logging/log4j/util/ProviderUtil.java',145,168,'lazyInit startup path')],'diff':'@@ ProviderUtil.lazyInit()\n- ServiceLoaderUtil.safeStream(...).forEach(ProviderUtil::addProvider);\n- for (...) { loadProvider(...); }\n+ final ProviderCatalog catalog = ProviderCatalog.loadOnce();\n+ catalog.providers().forEach(ProviderUtil::addProvider);\n+ PROVIDER = selectProvider(PropertiesUtil.getProperties(), catalog.providers(), LOGGER);'},
{'title':'4. ThreadContext and DefaultThreadContextMap per-call map churn','analysis':'Thread context is touched on hot logging paths. Copy-on-write behavior is safe, but expensive when updates are frequent.','sources':[('GitRepos/logging-log4j2-2.x/log4j-api/src/main/java/org/apache/logging/log4j/ThreadContext.java',238,278,'put and putAll delegation'),('GitRepos/logging-log4j2-2.x/log4j-api/src/main/java/org/apache/logging/log4j/spi/DefaultThreadContextMap.java',78,132,'copyAndPut path')],'diff':'@@ DefaultThreadContextMap.put(...)\n- localState.set(getMap(state).copyAndPut(key, value).getBackingArray());\n+ localState.set(getMap(state).mutateOrCopy(key, value).getBackingArray());\n@@ ThreadContext.putAll(...)\n+ contextMap.putAllIfSupported(m);'},
{'title':'5. Unbox ring-buffer and property lookup path','analysis':'Unbox matters because it sits on very hot logging paths. Property reads and ring-buffer sizing should happen once, cheaply.','sources':[('GitRepos/logging-log4j2-2.x/log4j-api/src/main/java/org/apache/logging/log4j/util/Unbox.java',115,142,'Ring-buffer sizing path')],'diff':'@@ Unbox.calculateRingBufferSize(...)\n- final String userPreferredRBSize = PropertiesUtil.getProperties().getStringProperty(...);\n+ final PropertiesUtil props = PropertiesUtil.getProperties();\n+ final String userPreferredRBSize = props.getStringProperty(...);\n- return ceilingNextPowerOfTwo(size);\n+ return cachedPowerOfTwo(size);'},
{'title':'6. CommandLine nested option parsing','analysis':'This is the single highest-scoring static hotspot in the repo. Parsing loops and style parsing both show repeated splitting and rescanning.','sources':[('GitRepos/logging-log4j2-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/tools/picocli/CommandLine.java',2156,2169,'Argument processing loop'),('GitRepos/logging-log4j2-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/tools/picocli/CommandLine.java',5031,5048,'Style.parse split loop')],'diff':'@@ CommandLine.Interpreter\n- String arg = args.pop();\n+ final String arg = args.pop();\n+ final ArgKind kind = classify(arg);\n@@ Style.parse(...)\n- final String[] codes = commaSeparatedCodes.split(",");\n+ final List<StringSlice> codes = splitViews(commaSeparatedCodes, COMMA);'},
{'title':'7. ScriptManager script-engine enumeration and dispatch','analysis':'ScriptManager repeatedly walks engine factories and builds language name strings. That is expensive setup work if scripts are touched often.','sources':[('GitRepos/logging-log4j2-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/script/ScriptManager.java',108,145,'Factory and name enumeration')],'diff':'@@ ScriptManager\n- for (final ScriptEngineFactory factory : factories) {\n-     for (final String name : factory.getNames()) { ... }\n- }\n+ final Map<String, ScriptEngineFactory> allowedFactoryIndex = indexAllowedFactories(factories, allowedLanguages);'},
{'title':'8. Rfc5424Layout field formatting and payload construction','analysis':'Structured logging paths often pay for map creation and formatter iteration for every event.','sources':[('GitRepos/logging-log4j2-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/layout/Rfc5424Layout.java',894,918,'FieldFormatter per-event map construction')],'diff':'@@ Rfc5424Layout.FieldFormatter.format(...)\n- final Map<String, String> map = new HashMap<>(delegateMap.size());\n+ final ReusableStringMap map = mutableContextMap(delegateMap.size());\n- final StringBuilder buffer = new StringBuilder();\n+ final StringBuilder buffer = threadLocalBuffer();\n+ buffer.setLength(0);'},
{'title':'9. DefaultMergeStrategy, MapFilter, and StructuredDataFilter repeated scans','analysis':'These configuration and filtering paths all show repeated list scans, repeated key or value checks, and temporary object churn.','sources':[('GitRepos/logging-log4j2-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/config/composite/DefaultMergeStrategy.java',150,215,'Logger child merge loops'),('GitRepos/logging-log4j2-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/filter/MapFilter.java',98,121,'MapFilter repeated contains checks'),('GitRepos/logging-log4j2-2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/filter/StructuredDataFilter.java',94,146,'StructuredDataFilter builder reuse')],'diff':'@@ DefaultMergeStrategy\n+ final Map<String, Node> targetChildren = indexChildren(targetNode);\n@@ MapFilter\n- ((List<String>) map.getValueAt(i)).contains(toMatch)\n+ candidateSets[i].contains(toMatch)\n@@ StructuredDataFilter\n- StringBuilder result = threadLocalStringBuilder.get();\n+ StringBuilder result = pooledBuilder();'},
{'title':'10. Log4j harness still needs a purer long-running API profile','analysis':'Even after narrowing the suite, the profile still reflects framework setup more than sustained library work.','sources':[('flamegraph/repos.json',62,79,'Current Log4j workload config')],'diff':'@@ flamegraph/repos.json\n- "tests": ["PropertiesUtilTest", "ProviderUtilTest", "ThreadContextTest", ...]\n+ "tests": ["PropertiesUtilTest", "ProviderUtilTest", "ThreadContextTest"],\n+ "repeat": 100,\n+ "custom_driver": "log4j_api_hot_loop"'}
]}
]

parts = []
for repo in repos:
    cards = []
    for item in repo['items']:
        src = []
        for rel_path, start, end, label in item['sources']:
            src.append(f"<div class='code-panel'><div class='code-label'>{escape(label)} <span>{escape(rel_path)}:{start}-{end}</span></div><pre><code>{escape(sn(rel_path, start, end))}</code></pre></div>")
        cards.append(f"<article class='issue-card'><div class='issue-head'><h5>{escape(item['title'])}</h5><span class='badge'>Potential refactor</span></div><p class='analysis'>{escape(item['analysis'])}</p><div class='code-grid'><div><div class='panel-title'>Related source</div>{''.join(src)}</div><div><div class='panel-title'>Hypothetical diff</div><div class='code-panel diff'><pre><code>{escape(item['diff'])}</code></pre></div></div></div></article>")
    parts.append(f"<section class='repo-section'><div class='repo-band'><h3>{escape(repo['name'])}</h3><p>{escape(repo['summary'])}</p></div>{''.join(cards)}</section>")

html = f"""<!DOCTYPE html>
<html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0' />
<title>Talk Overview With Refactor Diffs</title>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css'>
<link rel='preconnect' href='https://fonts.googleapis.com'><link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>
<link href='https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;700;800&family=IBM+Plex+Mono:wght@400;500&display=swap' rel='stylesheet'>
<style>
:root{{--bg:#f6f1e9;--surface:rgba(255,252,247,.96);--surface-strong:#fffdfa;--ink:#20312b;--muted:#607069;--line:#e7dcc8;--shadow-soft:0 10px 24px rgba(32,42,37,.08);--brand:#c26a07;--brand-deep:#163d34;--teal:#1f766b;--diff-bg:#fffaf3;}}
body{{font-family:'Manrope',sans-serif;color:var(--ink);background:radial-gradient(circle at top left,rgba(245,158,11,.16),transparent 22%),radial-gradient(circle at top right,rgba(15,118,110,.14),transparent 30%),linear-gradient(180deg,#faf5ec 0%,var(--bg) 100%);}}
.container{{width:min(1480px,95vw);}}header{{padding:28px 0 16px;}}.hero{{border-radius:30px;padding:34px;color:#fff;background:linear-gradient(135deg,#163d34 0%,#1f5a4f 50%,#c26a07 145%);box-shadow:0 24px 54px rgba(22,61,52,.2);}}.hero h2{{margin:0 0 12px;font-weight:800;letter-spacing:-.03em;}}.hero p{{margin:0;max-width:1080px;line-height:1.65;color:rgba(255,255,255,.93);}}
.repo-band{{margin:30px 0 16px;padding:18px 22px;border-radius:22px;background:linear-gradient(90deg,#fff8ef 0%,#fffdf9 100%);border-left:6px solid var(--brand);box-shadow:var(--shadow-soft);}}.repo-band h3{{margin:0 0 6px;font-size:1.7rem;font-weight:800;letter-spacing:-.03em;}}.repo-band p{{margin:0;color:var(--muted);line-height:1.6;}}
.issue-card{{background:var(--surface);border:1px solid rgba(194,106,7,.08);border-radius:24px;box-shadow:var(--shadow-soft);padding:20px 20px 18px;margin-bottom:16px;}}.issue-head{{display:flex;justify-content:space-between;gap:14px;align-items:start;}}.issue-head h5{{margin:0;font-size:1.08rem;font-weight:800;letter-spacing:-.02em;}}.badge{{background:#efe8ff;color:#5b2cb9;border-radius:999px;padding:7px 11px;font-size:.76rem;font-weight:800;}}.analysis{{margin:10px 0 16px;color:#30403a;line-height:1.6;}}
.code-grid{{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px;}}.panel-title{{font-size:.82rem;font-weight:800;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);margin:0 0 8px;}}.code-panel{{background:var(--surface-strong);border-radius:18px;box-shadow:inset 0 0 0 1px rgba(22,61,52,.08);overflow:hidden;margin-bottom:12px;}}.code-panel.diff{{background:var(--diff-bg);}}.code-label{{display:flex;justify-content:space-between;gap:10px;padding:10px 14px;background:rgba(31,118,107,.06);font-size:.8rem;font-weight:700;color:var(--brand-deep);border-bottom:1px solid rgba(22,61,52,.08);}}.code-label span{{color:var(--muted);font-weight:600;}}pre{{margin:0;padding:14px 16px;overflow-x:auto;font-family:'IBM Plex Mono',monospace;font-size:.88rem;line-height:1.55;color:#183028;background:transparent;}}footer{{margin:40px 0 30px;padding:16px 18px;border-radius:18px;background:rgba(255,255,255,.65);color:var(--muted);box-shadow:inset 0 0 0 1px rgba(194,106,7,.08);}}@media (max-width:980px){{.code-grid{{grid-template-columns:1fr;}}}}
</style></head>
<body><div class='container'><header><div class='hero'><h2>Talk Examples Overview With Source-Grounded Refactor Diffs</h2><p>For every top-10 point, this page now shows the related code, a short analysis of why it is expensive, and a hypothetical diff illustrating what a performance-oriented refactor could look like. The diffs are proposals, not claims that upstream already implemented them.</p></div></header>{''.join(parts)}<footer>Generated from TOP_10_ISSUES_PER_REPO.md, the local GitRepos source trees, and the current profiling harness files under flamegraph.</footer></div></body></html>"""
(root / 'talk_examples_overview.html').write_text(html, encoding='utf-8')
print('wrote talk_examples_overview.html')
